<a href="https://colab.research.google.com/github/HY-BME/bme_test_files/blob/%EB%8D%B0%EC%9D%B4%ED%84%B0%EA%B8%B0%EB%B0%98%ED%97%AC%EC%8A%A4%EC%BC%80%EC%96%B4%EA%B8%B0%EC%88%A0/class_0317.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd

# 데이터 로드
df = pd.read_csv('/content/sample_data/raw_medical_data.csv')

print("정제 전 컬럼명:", df.columns.tolist())
# 결과: [' Patient_ID ', 'Age', ' hr ', 'OX ']

정제 전 컬럼명: [' Patient_ID ', 'Age', ' hr ', 'OX ']

In [23]:
df

#hr : 심박수
#OX : 산소포화농도

    Patient_ID   Age    hr     OX
0         P-001   65   85.9   96.2
1         P-002   22   57.9   96.7
2         P-003   48   73.3   95.3
3         P-004   54   64.7   93.8
4         P-005   58    NaN   99.5
5         P-006   37   41.4   95.6
6         P-007   39   53.7  100.3
7         P-008   62   66.6   98.6
8         P-009   79   86.1   96.4
9         P-010   77   72.9   94.8
10        P-011   42   75.0   95.5
11        P-012   53    NaN   94.6
12        P-013   52   64.4  101.2
13        P-014   69   78.4   97.3
14        P-015   67   65.3   99.3
15        P-016   29   54.3   94.5
16        P-017   52    NaN   97.4
17        P-018   66   81.9   99.4
18        P-019   52   79.1   96.3
19        P-020   67   74.9   99.1
20        P-021   45  103.7   94.8
21        P-022   39   80.0   94.3
22        P-023   34   86.7   97.8
23        P-024   56  101.9   96.2
24        P-025   52   59.5   98.3
25        P-026   36   62.5   93.0
26        P-027   24   95.9   98.4
27        P-028   69   65.4  102.2
28        P-029   75   75.4   97.0
29        P-030   23   87.8   97.1
30        P-031   22   85.7   97.4
31        P-032   40   96.1   93.3
32        P-033   59   92.9   97.9
33        P-034   22   87.8   93.8
34        P-035   40   65.7   96.1
35        P-036   67   84.5   99.5
36        P-037   76   78.8   95.5
37        P-038   68   59.1   98.0
38        P-039   27   92.0   99.0
39        P-040   61   84.7   97.6
40        P-041   55   75.5   94.3
41        P-042   48   72.2   96.3
42        P-043   72   60.6  100.9
43        P-044   58   77.4   92.9
44        P-045   53   80.6   96.4
45        P-046   41   65.0   95.9
46        P-047   74   88.9   97.2
47        P-048   50   61.8   98.5
48        P-049   47   49.5  100.2
49        P-050   54   87.5   96.5

In [24]:
#공백제거 및 소문자 변환
df.columns = df.columns.str.strip().str.lower();
#컬럼명 일괄 변경
df.rename(columns={'hr': 'heart_rate', 'ox' : 'spo2'}, inplace=True);

df

   patient_id  age  heart_rate   spo2
0       P-001   65        85.9   96.2
1       P-002   22        57.9   96.7
2       P-003   48        73.3   95.3
3       P-004   54        64.7   93.8
4       P-005   58         NaN   99.5
5       P-006   37        41.4   95.6
6       P-007   39        53.7  100.3
7       P-008   62        66.6   98.6
8       P-009   79        86.1   96.4
9       P-010   77        72.9   94.8
10      P-011   42        75.0   95.5
11      P-012   53         NaN   94.6
12      P-013   52        64.4  101.2
13      P-014   69        78.4   97.3
14      P-015   67        65.3   99.3
15      P-016   29        54.3   94.5
16      P-017   52         NaN   97.4
17      P-018   66        81.9   99.4
18      P-019   52        79.1   96.3
19      P-020   67        74.9   99.1
20      P-021   45       103.7   94.8
21      P-022   39        80.0   94.3
22      P-023   34        86.7   97.8
23      P-024   56       101.9   96.2
24      P-025   52        59.5   98.3
25      P-026   36        62.5   93.0
26      P-027   24        95.9   98.4
27      P-028   69        65.4  102.2
28      P-029   75        75.4   97.0
29      P-030   23        87.8   97.1
30      P-031   22        85.7   97.4
31      P-032   40        96.1   93.3
32      P-033   59        92.9   97.9
33      P-034   22        87.8   93.8
34      P-035   40        65.7   96.1
35      P-036   67        84.5   99.5
36      P-037   76        78.8   95.5
37      P-038   68        59.1   98.0
38      P-039   27        92.0   99.0
39      P-040   61        84.7   97.6
40      P-041   55        75.5   94.3
41      P-042   48        72.2   96.3
42      P-043   72        60.6  100.9
43      P-044   58        77.4   92.9
44      P-045   53        80.6   96.4
45      P-046   41        65.0   95.9
46      P-047   74        88.9   97.2
47      P-048   50        61.8   98.5
48      P-049   47        49.5  100.2
49      P-050   54        87.5   96.5

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   patient_id  50 non-null     object
 1   age         50 non-null     int64
 2   heart_rate  47 non-null     float64
 3   spo2        50 non-null     float64
dtypes: float64(2), int64(1), object(1)
memory usage: 1.7+ KB

In [26]:
df['spo2'] = pd.to_numeric(df['spo2'], errors='coerce') #object type을 float로 치환
df.info()

df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   patient_id  50 non-null     object
 1   age         50 non-null     int64
 2   heart_rate  47 non-null     float64
 3   spo2        50 non-null     float64
dtypes: float64(2), int64(1), object(1)
memory usage: 1.7+ KB

   patient_id  age  heart_rate   spo2
0       P-001   65        85.9   96.2
1       P-002   22        57.9   96.7
2       P-003   48        73.3   95.3
3       P-004   54        64.7   93.8
4       P-005   58         NaN   99.5
5       P-006   37        41.4   95.6
6       P-007   39        53.7  100.3
7       P-008   62        66.6   98.6
8       P-009   79        86.1   96.4
9       P-010   77        72.9   94.8
10      P-011   42        75.0   95.5
11      P-012   53         NaN   94.6
12      P-013   52        64.4  101.2
13      P-014   69        78.4   97.3
14      P-015   67        65.3   99.3
15      P-016   29        54.3   94.5
16      P-017   52         NaN   97.4
17      P-018   66        81.9   99.4
18      P-019   52        79.1   96.3
19      P-020   67        74.9   99.1
20      P-021   45       103.7   94.8
21      P-022   39        80.0   94.3
22      P-023   34        86.7   97.8
23      P-024   56       101.9   96.2
24      P-025   52        59.5   98.3
25      P-026   36        62.5   93.0
26      P-027   24        95.9   98.4
27      P-028   69        65.4  102.2
28      P-029   75        75.4   97.0
29      P-030   23        87.8   97.1
30      P-031   22        85.7   97.4
31      P-032   40        96.1   93.3
32      P-033   59        92.9   97.9
33      P-034   22        87.8   93.8
34      P-035   40        65.7   96.1
35      P-036   67        84.5   99.5
36      P-037   76        78.8   95.5
37      P-038   68        59.1   98.0
38      P-039   27        92.0   99.0
39      P-040   61        84.7   97.6
40      P-041   55        75.5   94.3
41      P-042   48        72.2   96.3
42      P-043   72        60.6  100.9
43      P-044   58        77.4   92.9
44      P-045   53        80.6   96.4
45      P-046   41        65.0   95.9
46      P-047   74        88.9   97.2
47      P-048   50        61.8   98.5
48      P-049   47        49.5  100.2
49      P-050   54        87.5   96.5

In [27]:
#결측값 처리
print(df.isnull())

#결측값 개수 확인
print(df.isnull().sum())

patient_id    0
age           0
heart_rate    3
spo2          0
dtype: int64

In [35]:
#결측치 행 삭제
#df_cleaned = df.dropna(subset=['heart_rate'])

#결측값 대체
#심박수 평균값으로 결측치 채우기
df['heart_rate'] = df['heart_rate'].fillna(df['heart_rate'].mean())

# 시계열 데이터의 경우, 이전 값으로 채우기 (Forward Fill)
#df['spo2'] = df['spo2'].fillna(method='ffill')

df.isnull().sum()

patient_id    0
age           0
heart_rate    0
spo2          0
dtype: int64

In [36]:
#이상치 처리 - 생리학적으로 불가능한 수치나 기계적 오류

# Q1 = df['heart_rate'].quantile(0.25)
# Q3 = df['heart_rate'].quantile(0.75)
# IQR = Q3 - Q1

# # IQR 범위를 벗어나는 데이터 필터링
# lower_bound = Q1 - 1.5 * IQR #1.5배 만큼의 거리 최소
# upper_bound = Q3 + 1.5 * IQR #1.5배 만큼의 거리 최대

# df_final = df[(df['heart_rate'] >= lower_bound) & (df['heart_rate'] <= upper_bound)]

#spo2 기준
Q1 = df['spo2'].quantile(0.25)
Q3 = df['spo2'].quantile(0.75)
IQR = Q3 - Q1

# IQR 범위를 벗어나는 데이터 필터링
lower_bound = Q1 - 1.5 * IQR #1.5배 만큼의 거리 최소
upper_bound = Q3 + 1.5 * IQR #1.5배 만큼의 거리 최대

df_final = df[(df['spo2'] >= lower_bound) & (df['spo2'] <= upper_bound)]

df.describe()

             age  heart_rate        spo2
count  50.000000   50.000000   50.000000
mean   51.540000   75.338298   96.962000
std    16.152601   13.704454    2.224987
min    22.000000   41.400000   92.900000
25%    40.000000   65.075000   95.500000
50%    52.500000   75.369149   96.850000
75%    65.750000   85.850000   98.475000
max    79.000000  103.700000  102.200000

In [40]:
df_final = df_final[(df_final['spo2'] >= 0) & (df_final['spo2'] <= 100)] #산소포화도 0이상 100이하
df_final

   patient_id  age  heart_rate  spo2
0       P-001   65   85.900000  96.2
1       P-002   22   57.900000  96.7
2       P-003   48   73.300000  95.3
3       P-004   54   64.700000  93.8
4       P-005   58   75.338298  99.5
5       P-006   37   41.400000  95.6
7       P-008   62   66.600000  98.6
8       P-009   79   86.100000  96.4
9       P-010   77   72.900000  94.8
10      P-011   42   75.000000  95.5
11      P-012   53   75.338298  94.6
13      P-014   69   78.400000  97.3
14      P-015   67   65.300000  99.3
15      P-016   29   54.300000  94.5
16      P-017   52   75.338298  97.4
17      P-018   66   81.900000  99.4
18      P-019   52   79.100000  96.3
19      P-020   67   74.900000  99.1
20      P-021   45  103.700000  94.8
21      P-022   39   80.000000  94.3
22      P-023   34   86.700000  97.8
23      P-024   56  101.900000  96.2
24      P-025   52   59.500000  98.3
25      P-026   36   62.500000  93.0
26      P-027   24   95.900000  98.4
28      P-029   75   75.400000  97.0
29      P-030   23   87.800000  97.1
30      P-031   22   85.700000  97.4
31      P-032   40   96.100000  93.3
32      P-033   59   92.900000  97.9
33      P-034   22   87.800000  93.8
34      P-035   40   65.700000  96.1
35      P-036   67   84.500000  99.5
36      P-037   76   78.800000  95.5
37      P-038   68   59.100000  98.0
38      P-039   27   92.000000  99.0
39      P-040   61   84.700000  97.6
40      P-041   55   75.500000  94.3
41      P-042   48   72.200000  96.3
43      P-044   58   77.400000  92.9
44      P-045   53   80.600000  96.4
45      P-046   41   65.000000  95.9
46      P-047   74   88.900000  97.2
47      P-048   50   61.800000  98.5
49      P-050   54   87.500000  96.5