<a href="https://colab.research.google.com/github/HY-BME/bme_test_files/blob/%EB%B0%94%EC%9D%B4%EC%98%A4%EA%B3%B5%ED%95%99%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4%EA%B8%B0%EC%88%A0/ML_0312.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

# CSV 파일 불러오기
df = pd.read_csv("/content/sample_data/data.csv")

df.describe()

             id      price      stock
count  20.00000  18.000000  20.000000
mean   10.50000  57.100000  28.200000
std     5.91608  29.728522  15.164363
min     1.00000  18.700000   1.000000
25%     5.75000  35.545000  13.250000
50%    10.50000  50.525000  34.500000
75%    15.25000  89.577500  37.500000
max    20.00000  99.200000  48.000000

In [5]:
df

# 3	Item_3	Category_3	NaN	1 --- NaN : 결측치(대부분 레코드를 삭제함).
# 만약 결측치가 많을 경우 다른 값으로 치환시킴 - missing value를 fill한다. -> 전체 데이터의 평균값으로 채움(왜곡의 오류를 줄인다)
# 또는 이전값을 넣거나 주변값의 평균값을 넣는다

    id     name    category  price  stock
0    1   Item_1  Category_3  18.70     43
1    2   Item_2  Category_3  68.38     39
2    3   Item_3  Category_3    NaN      1
3    4   Item_4  Category_3  51.88     14
4    5      NaN  Category_5  49.17      4
5    6   Item_6  Category_1  89.61     44
6    7   Item_7  Category_4  99.20     48
7    8   Item_8  Category_2  36.49      6
8    9   Item_9  Category_3  19.18     37
9   10  Item_10         NaN  98.91     32
10  11  Item_11  Category_4    NaN     32
11  12  Item_12  Category_2  95.71     34
12  13  Item_13  Category_2  27.81     11
13  14  Item_14  Category_5  20.11     10
14  15  Item_15  Category_5  35.23     21
15  16  Item_16  Category_4  90.41     35
16  17  Item_17         NaN  89.48     35
17  18  Item_18  Category_5  43.99     36
18  19  Item_19  Category_2  38.00     35
19  20  Item_20  Category_3  55.54     47

In [13]:
df.loc[2, "price"] = 57.1
df

    id     name    category  price  stock
0    1   Item_1  Category_3  18.70     43
1    2   Item_2  Category_3  68.38     39
2    3   Item_3  Category_3  57.10      1
3    4   Item_4  Category_3  51.88     14
4    5      NaN  Category_5  49.17      4
5    6   Item_6  Category_1  89.61     44
6    7   Item_7  Category_4  99.20     48
7    8   Item_8  Category_2  36.49      6
8    9   Item_9  Category_3  19.18     37
9   10  Item_10         NaN  98.91     32
10  11  Item_11  Category_4    NaN     32
11  12  Item_12  Category_2  95.71     34
12  13  Item_13  Category_2  27.81     11
13  14  Item_14  Category_5  20.11     10
14  15  Item_15  Category_5  35.23     21
15  16  Item_16  Category_4  90.41     35
16  17  Item_17         NaN  89.48     35
17  18  Item_18  Category_5  43.99     36
18  19  Item_19  Category_2  38.00     35
19  20  Item_20  Category_3  55.54     47

In [18]:
#mean_price = df['price'].mean()
df.fillna({'price': 0}, inplace = True)
df.fillna({'category': 'NULL'}, inplace = True)
df

    id     name    category  price  stock
0    1   Item_1  Category_3  18.70     43
1    2   Item_2  Category_3  68.38     39
2    3   Item_3  Category_3  57.10      1
3    4   Item_4  Category_3  51.88     14
4    5      NaN  Category_5  49.17      4
5    6   Item_6  Category_1  89.61     44
6    7   Item_7  Category_4  99.20     48
7    8   Item_8  Category_2  36.49      6
8    9   Item_9  Category_3  19.18     37
9   10  Item_10        NULL  98.91     32
10  11  Item_11  Category_4  57.10     32
11  12  Item_12  Category_2  95.71     34
12  13  Item_13  Category_2  27.81     11
13  14  Item_14  Category_5  20.11     10
14  15  Item_15  Category_5  35.23     21
15  16  Item_16  Category_4  90.41     35
16  17  Item_17        NULL  89.48     35
17  18  Item_18  Category_5  43.99     36
18  19  Item_19  Category_2  38.00     35
19  20  Item_20  Category_3  55.54     47

In [20]:
df['category']

0     Category_3
1     Category_3
2     Category_3
3     Category_3
4     Category_5
5     Category_1
6     Category_4
7     Category_2
8     Category_3
9           NULL
10    Category_4
11    Category_2
12    Category_2
13    Category_5
14    Category_5
15    Category_4
16          NULL
17    Category_5
18    Category_2
19    Category_3
Name: category, dtype: object

In [23]:
df[df['price'] > 50] #price가 50보다 큰 행들만 추출이됨

    id     name    category  price  stock
1    2   Item_2  Category_3  68.38     39
2    3   Item_3  Category_3  57.10      1
3    4   Item_4  Category_3  51.88     14
5    6   Item_6  Category_1  89.61     44
6    7   Item_7  Category_4  99.20     48
9   10  Item_10        NULL  98.91     32
10  11  Item_11  Category_4  57.10     32
11  12  Item_12  Category_2  95.71     34
15  16  Item_16  Category_4  90.41     35
16  17  Item_17        NULL  89.48     35
19  20  Item_20  Category_3  55.54     47