<a href="https://colab.research.google.com/github/HY-BME/bme_test_files/blob/%EB%B0%94%EC%9D%B4%EC%98%A4%EA%B3%B5%ED%95%99%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4%EA%B8%B0%EC%88%A0/ML_0312.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

# CSV 파일 불러오기
df = pd.read_csv("/content/sample_data/data.csv")

df.describe()

             id      price      stock
count  20.00000  18.000000  20.000000
mean   10.50000  57.100000  28.200000
std     5.91608  29.728522  15.164363
min     1.00000  18.700000   1.000000
25%     5.75000  35.545000  13.250000
50%    10.50000  50.525000  34.500000
75%    15.25000  89.577500  37.500000
max    20.00000  99.200000  48.000000

In [5]:
df

# 3	Item_3	Category_3	NaN	1 --- NaN : 결측치(대부분 레코드를 삭제함).
# 만약 결측치가 많을 경우 다른 값으로 치환시킴 - missing value를 fill한다. -> 전체 데이터의 평균값으로 채움(왜곡의 오류를 줄인다)
# 또는 이전값을 넣거나 주변값의 평균값을 넣는다

    id     name    category  price  stock
0    1   Item_1  Category_3  18.70     43
1    2   Item_2  Category_3  68.38     39
2    3   Item_3  Category_3    NaN      1
3    4   Item_4  Category_3  51.88     14
4    5      NaN  Category_5  49.17      4
5    6   Item_6  Category_1  89.61     44
6    7   Item_7  Category_4  99.20     48
7    8   Item_8  Category_2  36.49      6
8    9   Item_9  Category_3  19.18     37
9   10  Item_10         NaN  98.91     32
10  11  Item_11  Category_4    NaN     32
11  12  Item_12  Category_2  95.71     34
12  13  Item_13  Category_2  27.81     11
13  14  Item_14  Category_5  20.11     10
14  15  Item_15  Category_5  35.23     21
15  16  Item_16  Category_4  90.41     35
16  17  Item_17         NaN  89.48     35
17  18  Item_18  Category_5  43.99     36
18  19  Item_19  Category_2  38.00     35
19  20  Item_20  Category_3  55.54     47

In [6]:
df.loc[2, "price"] = 57.1
df

    id     name    category  price  stock
0    1   Item_1  Category_3  18.70     43
1    2   Item_2  Category_3  68.38     39
2    3   Item_3  Category_3  57.10      1
3    4   Item_4  Category_3  51.88     14
4    5      NaN  Category_5  49.17      4
5    6   Item_6  Category_1  89.61     44
6    7   Item_7  Category_4  99.20     48
7    8   Item_8  Category_2  36.49      6
8    9   Item_9  Category_3  19.18     37
9   10  Item_10         NaN  98.91     32
10  11  Item_11  Category_4    NaN     32
11  12  Item_12  Category_2  95.71     34
12  13  Item_13  Category_2  27.81     11
13  14  Item_14  Category_5  20.11     10
14  15  Item_15  Category_5  35.23     21
15  16  Item_16  Category_4  90.41     35
16  17  Item_17         NaN  89.48     35
17  18  Item_18  Category_5  43.99     36
18  19  Item_19  Category_2  38.00     35
19  20  Item_20  Category_3  55.54     47

In [7]:
#mean_price = df['price'].mean()
df.fillna({'price': 0}, inplace = True)
df.fillna({'category': 'NULL'}, inplace = True)
df

    id     name    category  price  stock
0    1   Item_1  Category_3  18.70     43
1    2   Item_2  Category_3  68.38     39
2    3   Item_3  Category_3  57.10      1
3    4   Item_4  Category_3  51.88     14
4    5      NaN  Category_5  49.17      4
5    6   Item_6  Category_1  89.61     44
6    7   Item_7  Category_4  99.20     48
7    8   Item_8  Category_2  36.49      6
8    9   Item_9  Category_3  19.18     37
9   10  Item_10        NULL  98.91     32
10  11  Item_11  Category_4   0.00     32
11  12  Item_12  Category_2  95.71     34
12  13  Item_13  Category_2  27.81     11
13  14  Item_14  Category_5  20.11     10
14  15  Item_15  Category_5  35.23     21
15  16  Item_16  Category_4  90.41     35
16  17  Item_17        NULL  89.48     35
17  18  Item_18  Category_5  43.99     36
18  19  Item_19  Category_2  38.00     35
19  20  Item_20  Category_3  55.54     47

In [8]:
df['category']

0     Category_3
1     Category_3
2     Category_3
3     Category_3
4     Category_5
5     Category_1
6     Category_4
7     Category_2
8     Category_3
9           NULL
10    Category_4
11    Category_2
12    Category_2
13    Category_5
14    Category_5
15    Category_4
16          NULL
17    Category_5
18    Category_2
19    Category_3
Name: category, dtype: object

In [9]:
df[df['price'] > 50] #price가 50보다 큰 행들만 추출이됨

    id     name    category  price  stock
1    2   Item_2  Category_3  68.38     39
2    3   Item_3  Category_3  57.10      1
3    4   Item_4  Category_3  51.88     14
5    6   Item_6  Category_1  89.61     44
6    7   Item_7  Category_4  99.20     48
9   10  Item_10        NULL  98.91     32
11  12  Item_12  Category_2  95.71     34
15  16  Item_16  Category_4  90.41     35
16  17  Item_17        NULL  89.48     35
19  20  Item_20  Category_3  55.54     47

In [10]:
df[df['price'] < 50] #price가 50보다 작은 행들만 추출이됨

    id     name    category  price  stock
0    1   Item_1  Category_3  18.70     43
4    5      NaN  Category_5  49.17      4
7    8   Item_8  Category_2  36.49      6
8    9   Item_9  Category_3  19.18     37
10  11  Item_11  Category_4   0.00     32
12  13  Item_13  Category_2  27.81     11
13  14  Item_14  Category_5  20.11     10
14  15  Item_15  Category_5  35.23     21
17  18  Item_18  Category_5  43.99     36
18  19  Item_19  Category_2  38.00     35

In [11]:
df['price'].describe()

count    20.000000
mean     54.245000
std      30.883257
min       0.000000
25%      33.375000
50%      50.525000
75%      89.512500
max      99.200000
Name: price, dtype: float64

In [12]:
# price 기준 정렬
df.sort_values(by="price")

    id     name    category  price  stock
10  11  Item_11  Category_4   0.00     32
0    1   Item_1  Category_3  18.70     43
8    9   Item_9  Category_3  19.18     37
13  14  Item_14  Category_5  20.11     10
12  13  Item_13  Category_2  27.81     11
14  15  Item_15  Category_5  35.23     21
7    8   Item_8  Category_2  36.49      6
18  19  Item_19  Category_2  38.00     35
17  18  Item_18  Category_5  43.99     36
4    5      NaN  Category_5  49.17      4
3    4   Item_4  Category_3  51.88     14
19  20  Item_20  Category_3  55.54     47
2    3   Item_3  Category_3  57.10      1
1    2   Item_2  Category_3  68.38     39
16  17  Item_17        NULL  89.48     35
5    6   Item_6  Category_1  89.61     44
15  16  Item_16  Category_4  90.41     35
11  12  Item_12  Category_2  95.71     34
9   10  Item_10        NULL  98.91     32
6    7   Item_7  Category_4  99.20     48

In [13]:
df.to_csv("/content/sample_data/new_data.csv", index=False)

In [14]:
df[["name", "category"]]

       name    category
0    Item_1  Category_3
1    Item_2  Category_3
2    Item_3  Category_3
3    Item_4  Category_3
4       NaN  Category_5
5    Item_6  Category_1
6    Item_7  Category_4
7    Item_8  Category_2
8    Item_9  Category_3
9   Item_10        NULL
10  Item_11  Category_4
11  Item_12  Category_2
12  Item_13  Category_2
13  Item_14  Category_5
14  Item_15  Category_5
15  Item_16  Category_4
16  Item_17        NULL
17  Item_18  Category_5
18  Item_19  Category_2
19  Item_20  Category_3

In [15]:
df.iloc[2] #행선택
df.loc[2] # 행선택

id                   3
name            Item_3
category    Category_3
price             57.1
stock                1
Name: 2, dtype: object

In [16]:
df.fillna(df["price"].mean())

    id     name    category  price  stock
0    1   Item_1  Category_3  18.70     43
1    2   Item_2  Category_3  68.38     39
2    3   Item_3  Category_3  57.10      1
3    4   Item_4  Category_3  51.88     14
4    5   54.245  Category_5  49.17      4
5    6   Item_6  Category_1  89.61     44
6    7   Item_7  Category_4  99.20     48
7    8   Item_8  Category_2  36.49      6
8    9   Item_9  Category_3  19.18     37
9   10  Item_10        NULL  98.91     32
10  11  Item_11  Category_4   0.00     32
11  12  Item_12  Category_2  95.71     34
12  13  Item_13  Category_2  27.81     11
13  14  Item_14  Category_5  20.11     10
14  15  Item_15  Category_5  35.23     21
15  16  Item_16  Category_4  90.41     35
16  17  Item_17        NULL  89.48     35
17  18  Item_18  Category_5  43.99     36
18  19  Item_19  Category_2  38.00     35
19  20  Item_20  Category_3  55.54     47

In [17]:
df[df["price"] > 50]

    id     name    category  price  stock
1    2   Item_2  Category_3  68.38     39
2    3   Item_3  Category_3  57.10      1
3    4   Item_4  Category_3  51.88     14
5    6   Item_6  Category_1  89.61     44
6    7   Item_7  Category_4  99.20     48
9   10  Item_10        NULL  98.91     32
11  12  Item_12  Category_2  95.71     34
15  16  Item_16  Category_4  90.41     35
16  17  Item_17        NULL  89.48     35
19  20  Item_20  Category_3  55.54     47

In [18]:
df["new_column_name"] = df["price"] * 1.2
df

    id     name    category  price  stock  new_column_name
0    1   Item_1  Category_3  18.70     43           22.440
1    2   Item_2  Category_3  68.38     39           82.056
2    3   Item_3  Category_3  57.10      1           68.520
3    4   Item_4  Category_3  51.88     14           62.256
4    5      NaN  Category_5  49.17      4           59.004
5    6   Item_6  Category_1  89.61     44          107.532
6    7   Item_7  Category_4  99.20     48          119.040
7    8   Item_8  Category_2  36.49      6           43.788
8    9   Item_9  Category_3  19.18     37           23.016
9   10  Item_10        NULL  98.91     32          118.692
10  11  Item_11  Category_4   0.00     32            0.000
11  12  Item_12  Category_2  95.71     34          114.852
12  13  Item_13  Category_2  27.81     11           33.372
13  14  Item_14  Category_5  20.11     10           24.132
14  15  Item_15  Category_5  35.23     21           42.276
15  16  Item_16  Category_4  90.41     35          108.492
16  17  Item_17        NULL  89.48     35          107.376
17  18  Item_18  Category_5  43.99     36           52.788
18  19  Item_19  Category_2  38.00     35           45.600
19  20  Item_20  Category_3  55.54     47           66.648

In [19]:
# 10번째 행 복사
row_to_insert = df.iloc[9].copy()
# 15번째 행에 붙여넣기
df = pd.concat([df.iloc[:14], pd.DataFrame([row_to_insert]), df.iloc[14:]], ignore_index=True)

df

    id     name    category  price  stock  new_column_name
0    1   Item_1  Category_3  18.70     43           22.440
1    2   Item_2  Category_3  68.38     39           82.056
2    3   Item_3  Category_3  57.10      1           68.520
3    4   Item_4  Category_3  51.88     14           62.256
4    5      NaN  Category_5  49.17      4           59.004
5    6   Item_6  Category_1  89.61     44          107.532
6    7   Item_7  Category_4  99.20     48          119.040
7    8   Item_8  Category_2  36.49      6           43.788
8    9   Item_9  Category_3  19.18     37           23.016
9   10  Item_10        NULL  98.91     32          118.692
10  11  Item_11  Category_4   0.00     32            0.000
11  12  Item_12  Category_2  95.71     34          114.852
12  13  Item_13  Category_2  27.81     11           33.372
13  14  Item_14  Category_5  20.11     10           24.132
14  10  Item_10        NULL  98.91     32          118.692
15  15  Item_15  Category_5  35.23     21           42.276
16  16  Item_16  Category_4  90.41     35          108.492
17  17  Item_17        NULL  89.48     35          107.376
18  18  Item_18  Category_5  43.99     36           52.788
19  19  Item_19  Category_2  38.00     35           45.600
20  20  Item_20  Category_3  55.54     47           66.648

In [20]:
df.drop_duplicates()

    id     name    category  price  stock  new_column_name
0    1   Item_1  Category_3  18.70     43           22.440
1    2   Item_2  Category_3  68.38     39           82.056
2    3   Item_3  Category_3  57.10      1           68.520
3    4   Item_4  Category_3  51.88     14           62.256
4    5      NaN  Category_5  49.17      4           59.004
5    6   Item_6  Category_1  89.61     44          107.532
6    7   Item_7  Category_4  99.20     48          119.040
7    8   Item_8  Category_2  36.49      6           43.788
8    9   Item_9  Category_3  19.18     37           23.016
9   10  Item_10        NULL  98.91     32          118.692
10  11  Item_11  Category_4   0.00     32            0.000
11  12  Item_12  Category_2  95.71     34          114.852
12  13  Item_13  Category_2  27.81     11           33.372
13  14  Item_14  Category_5  20.11     10           24.132
15  15  Item_15  Category_5  35.23     21           42.276
16  16  Item_16  Category_4  90.41     35          108.492
17  17  Item_17        NULL  89.48     35          107.376
18  18  Item_18  Category_5  43.99     36           52.788
19  19  Item_19  Category_2  38.00     35           45.600
20  20  Item_20  Category_3  55.54     47           66.648

In [21]:
df.to_excel("/content/sample_data/data.xlsx", index=False)

In [25]:
df.drop(columns=["new_column_name"])

    id     name    category  price  stock
0    1   Item_1  Category_3  18.70     43
1    2   Item_2  Category_3  68.38     39
2    3   Item_3  Category_3  57.10      1
3    4   Item_4  Category_3  51.88     14
4    5      NaN  Category_5  49.17      4
5    6   Item_6  Category_1  89.61     44
6    7   Item_7  Category_4  99.20     48
7    8   Item_8  Category_2  36.49      6
8    9   Item_9  Category_3  19.18     37
9   10  Item_10        NULL  98.91     32
10  11  Item_11  Category_4   0.00     32
11  12  Item_12  Category_2  95.71     34
12  13  Item_13  Category_2  27.81     11
13  14  Item_14  Category_5  20.11     10
14  10  Item_10        NULL  98.91     32
15  15  Item_15  Category_5  35.23     21
16  16  Item_16  Category_4  90.41     35
17  17  Item_17        NULL  89.48     35
18  18  Item_18  Category_5  43.99     36
19  19  Item_19  Category_2  38.00     35
20  20  Item_20  Category_3  55.54     47

In [23]:
df.to_json("/content/sample_data/data.json")

In [26]:
df.dropna(axis=0) #결측치가 있는 행 삭제

    id     name    category  price  stock  new_column_name
0    1   Item_1  Category_3  18.70     43           22.440
1    2   Item_2  Category_3  68.38     39           82.056
2    3   Item_3  Category_3  57.10      1           68.520
3    4   Item_4  Category_3  51.88     14           62.256
5    6   Item_6  Category_1  89.61     44          107.532
6    7   Item_7  Category_4  99.20     48          119.040
7    8   Item_8  Category_2  36.49      6           43.788
8    9   Item_9  Category_3  19.18     37           23.016
9   10  Item_10        NULL  98.91     32          118.692
10  11  Item_11  Category_4   0.00     32            0.000
11  12  Item_12  Category_2  95.71     34          114.852
12  13  Item_13  Category_2  27.81     11           33.372
13  14  Item_14  Category_5  20.11     10           24.132
14  10  Item_10        NULL  98.91     32          118.692
15  15  Item_15  Category_5  35.23     21           42.276
16  16  Item_16  Category_4  90.41     35          108.492
17  17  Item_17        NULL  89.48     35          107.376
18  18  Item_18  Category_5  43.99     36           52.788
19  19  Item_19  Category_2  38.00     35           45.600
20  20  Item_20  Category_3  55.54     47           66.648

In [27]:
df.dropna(axis=1) #결측치가 있는 열 삭제

    id    category  price  stock  new_column_name
0    1  Category_3  18.70     43           22.440
1    2  Category_3  68.38     39           82.056
2    3  Category_3  57.10      1           68.520
3    4  Category_3  51.88     14           62.256
4    5  Category_5  49.17      4           59.004
5    6  Category_1  89.61     44          107.532
6    7  Category_4  99.20     48          119.040
7    8  Category_2  36.49      6           43.788
8    9  Category_3  19.18     37           23.016
9   10        NULL  98.91     32          118.692
10  11  Category_4   0.00     32            0.000
11  12  Category_2  95.71     34          114.852
12  13  Category_2  27.81     11           33.372
13  14  Category_5  20.11     10           24.132
14  10        NULL  98.91     32          118.692
15  15  Category_5  35.23     21           42.276
16  16  Category_4  90.41     35          108.492
17  17        NULL  89.48     35          107.376
18  18  Category_5  43.99     36           52.788
19  19  Category_2  38.00     35           45.600
20  20  Category_3  55.54     47           66.648